language: node_js
os:
  - osx
  - linux
node_js: 8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 5;
    fi

install:
  - yarn
  - cd server && yarn
  - cd ..

script:
  - yarn test

after_success:
  - cd server && yarn coverage && cd ..

cache: yarn
